### ISSUE TITLE
Jcf Module willl not compile with Angular V5+

### ISSUE THREAD

**Issue by dominiquemiller** [TrimAgency/angular-jcf-module#7]
When compiling, either with 'ng build' or 'ng serve' get the following error: 
ERROR in ./node_modules/angular2-jcf-directive/jcfModule/index.ts
Module build failed: Error: /Users/mr1monkey/Documents/trim_projects/trim-ng2-starter/node_modules/angular2-jcf-directive/jcfModule/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/Users/mr1monkey/Documents/trim_projects/trim-ng2-starter/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:624:23)
    at plugin.done.then (/Users/mr1monkey/Documents/trim_projects/trim-ng2-starter/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 12:0-61
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by dominiquemiller** [comment]
Fixed in PR [#8](https://github.com/TrimAgency/angular-jcf-module/pull/8).
- bumped version to 0.5.3
- tested with Angular 5.
